server:
  port: 8080

logging:
  level:
    root: info

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        generate_statistics: true
#        order_inserts: true
#        jdbc:
#          batch_size: 50

    show-sql: false
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?sslmode=disable&search_path=public;
    username: postgres
    password: postgres
    #    password: admin
    driver-class-name: org.postgresql.Driver


#monitoring-folder: C:\\Users\\jcarlos\\AppData\\Local\\PokerStars.EE\\HandHistory\\jcarlosvale
monitoring-folder: C:\\Pessoal\\Projects\\pokerReader\\src\\test\\resources\\top
monitoring-interval: 3000
consolidated-file-directory: c:\\temp
html-directory: c:\\temp
page-size: 30